version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: tracking-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=tracking_db
    ports:
      - "5432:5432"